nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
      - "code-runtime"
    volumes:
      - ~/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
      - "redis"
      - "code-runtime"
    volumes:
      - ~/opt:/opt

code-runtime:
    build: ./code-runtime
    links:
      - "php"
      - "offline"
      - "nginx"
    volumes:
      - ~/opt:/opt

offline:
    build: ./offline
    links:
      - "redis"
      - "memcache"
      - "mysql"
    volumes:
      - ~/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"
